version: '3'

services:
  redis-node-1:
    image: redis:7-alpine
    command: [ "redis-server", "--port", "7000", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    ports: [ "7000:7000" ]
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:7-alpine
    command: [ "redis-server", "--port", "7001", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    ports: [ "7001:7001" ]
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:7-alpine
    command: [ "redis-server", "--port", "7002", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    ports: [ "7002:7002" ]
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:7-alpine
    command: [ "redis-server", "--port", "7003", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    ports: [ "7003:7003" ]
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:7-alpine
    command: [ "redis-server", "--port", "7004", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    ports: [ "7004:7004" ]
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:7-alpine
    command: [ "redis-server", "--port", "7005", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    ports: [ "7005:7005" ]
    networks:
      - redis-cluster

  cluster-creator:
    image: redis:7-alpine
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    command: >
      sh -c "sleep 5; echo 'yes' | redis-cli --cluster create  redis-node-1:7000  redis-node-2:7001  redis-node-3:7002  redis-node-4:7003  redis-node-5:7004  redis-node-6:7005  --cluster-replicas 1; sleep infinity"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
